export const GET_HOME_PAGE_DATA_REQUEST = 'GET_HOME_PAGE_DATA_REQUEST';
export const GET_HOME_PAGE_DATA_REQUEST_SUCCESS = 'GET_HOME_PAGE_DATA_REQUEST_SUCCESS';
export const GET_HOME_PAGE_DATA_REQUEST_ERROR = 'GET_HOME_PAGE_DATA_REQUEST_ERROR';
